### ISSUE TITLE
where is the tensor name in the training file(run_classifier.py)?

### ISSUE THREAD

**Issue by xljhtq** [bigboNed3/bert_serving#11]
Hi: 
    where are the tensor names, such as  input_ids_1 ,  input_mask_1 and so on . the test code is as follows:      
![image](https://user-images.githubusercontent.com/30365798/54668851-dec9fd80-4b2a-11e9-8f03-a23cb0e077c9.png)

     I cannot find anywhere in the file "run_classifier.py" . please tell me about it, thanks!

**Comment by practicingman** [comment]
> Hi:
> where are the tensor names, such as input_ids_1 , input_mask_1 and so on . the test code is as follows:
> ![image](https://user-images.githubusercontent.com/30365798/54668851-dec9fd80-4b2a-11e9-8f03-a23cb0e077c9.png)
> 
> ```
>  I cannot find anywhere in the file "run_classifier.py" . please tell me about it, thanks!
> ```
I haven't use tensorflow for a while, but
```bash
saved_model_cli show --all --dir $exported_dir
```
should work
