### ISSUE TITLE
gRPC client issue

### ISSUE THREAD

**Issue by shawei3000** [bigboNed3/bert_serving#2]
**I exported the model using the suggested serving function (unique_ids instead of label_id), as below: 
saved_model_cli show --all --dir /$model_saved_dire:**

_signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['input_ids'] tensor_info:
        dtype: DT_INT32
        shape: (-1, 320)
        name: input_ids_1:0
    inputs['input_mask'] tensor_info:
        dtype: DT_INT32
        shape: (-1, 320)
        name: input_mask_1:0
    inputs['segment_ids'] tensor_info:
        dtype: DT_INT32
        shape: (-1, 320)
        name: segment_ids_1:0
    inputs['unique_ids'] tensor_info:
        dtype: DT_INT32
        shape: (-1)
        name: unique_ids_1:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['end_logits'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 320)
        name: unstack:1
    outputs['start_logits'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 320)
        name: unstack:0
    outputs['unique_ids'] tensor_info:
        dtype: DT_INT32
        shape: (-1)
        name: unique_ids_1:0_

**RPC server started on 8500 successfully, however, when I call through RPC client, I got  error:**
url_port='0.0.0.0:8500'
channel = grpc.insecure_channel(url_port)
-- #data is prepared following the standard...
...
request.inputs['input_ids'].CopyFrom(tf.contrib.util.make_tensor_proto(data.input_ids, shape=[ 320], dtype=tf.int32))
request.inputs['input_mask'].CopyFrom(tf.contrib.util.make_tensor_proto(data.input_mask, shape=[ 320], dtype=tf.int32))
request.inputs['segment_ids'].CopyFrom(tf.contrib.util.make_tensor_proto(data.segment_ids, shape=[ 320], dtype=tf.int32))
request.inputs['unique_ids'].CopyFrom(tf.contrib.util.make_tensor_proto(data.unique_id, shape=[ 1], dtype=tf.int32))

predict_response = stub.Predict(request, timeout=10.)   

**ERROR:**
  raise _Rendezvous(state, None, None, deadline)
_Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.INVALID_ARGUMENT, unique_ids_1:0 is both fed and fetched.)>

**My question:**
is this because name ("unique_ids") conflict between input and output? how do I go around it?

**Comment by practicingman** [comment]
> **I exported the model using the suggested serving function (unique_ids instead of label_id), as below: saved_model_cli show --all --dir /$model_saved_dire:**
> 
> _signature_def['serving_default']: The given SavedModel SignatureDef contains the following input(s): inputs['input_ids'] tensor_info: dtype: DT_INT32 shape: (-1, 320) name: input_ids_1:0 inputs['input_mask'] tensor_info: dtype: DT_INT32 shape: (-1, 320) name: input_mask_1:0 inputs['segment_ids'] tensor_info: dtype: DT_INT32 shape: (-1, 320) name: segment_ids_1:0 inputs['unique_ids'] tensor_info: dtype: DT_INT32 shape: (-1) name: unique_ids_1:0 The given SavedModel SignatureDef contains the following output(s): outputs['end_logits'] tensor_info: dtype: DT_FLOAT shape: (-1, 320) name: unstack:1 outputs['start_logits'] tensor_info: dtype: DT_FLOAT shape: (-1, 320) name: unstack:0 outputs['unique_ids'] tensor_info: dtype: DT_INT32 shape: (-1) name: unique_ids_1:0_
> 
> **RPC server started on 8500 successfully, however, when I call through RPC client, I got error:**
> url_port='0.0.0.0:8500'
> channel = grpc.insecure_channel(url_port)
> -- #data is prepared following the standard...
> ...
> request.inputs['input_ids'].CopyFrom(tf.contrib.util.make_tensor_proto(data.input_ids, shape=[ 320], dtype=tf.int32))
> request.inputs['input_mask'].CopyFrom(tf.contrib.util.make_tensor_proto(data.input_mask, shape=[ 320], dtype=tf.int32))
> request.inputs['segment_ids'].CopyFrom(tf.contrib.util.make_tensor_proto(data.segment_ids, shape=[ 320], dtype=tf.int32))
> request.inputs['unique_ids'].CopyFrom(tf.contrib.util.make_tensor_proto(data.unique_id, shape=[ 1], dtype=tf.int32))
> 
> predict_response = stub.Predict(request, timeout=10.)
> 
> **ERROR:**
> raise _Rendezvous(state, None, None, deadline)
> _Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.INVALID_ARGUMENT, unique_ids_1:0 is both fed and fetched.)>
> 
> **My question:**
> is this because name ("unique_ids") conflict between input and output? how do I go around it?

seems this problem is related to tensorflow.
checkout https://stackoverflow.com/questions/39307108/placeholder-20-is-both-fed-and-fetched
google search 'tensorflow fed and fetched'.

**Comment by shawei3000** [comment]
Hi, bigboNed3:
Thanks! 
A. adding following line in computational graph appears solved the problem (unique_ids_1:0 is both fed and fetched):
unique_ids = tf.identity(unique_ids)

B. I re-exported the model, started gRPC service, and call the service again, exactly the same as above, got another error as below during prediction:
request.inputs['input_ids'].CopyFrom(tf.contrib.util.make_tensor_proto(data.input_ids, shape=[ 320], dtype=tf.int32))
request.inputs['input_mask'].CopyFrom(tf.contrib.util.make_tensor_proto(data.input_mask, shape=[ 320], dtype=tf.int32))
request.inputs['segment_ids'].CopyFrom(tf.contrib.util.make_tensor_proto(data.segment_ids, shape=[ 320], dtype=tf.int32))
request.inputs['unique_ids'].CopyFrom(tf.contrib.util.make_tensor_proto([100000], shape=[ 1], dtype=tf.int32))
predict_response = stub.Predict(request, timeout=10.)
:

### __Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.INVALID_ARGUMENT, Input to reshape is a tensor with 320 values, but the requested shape has 102400
	 [[{{node bert/encoder/Reshape}} = Reshape[T=DT_INT32, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](_arg_input_mask_1_0_1/_809, bert/encoder/Reshape/shape)]]
	 [[{{node unstack/_815}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3350_unstack", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]])>_

I reviewed the data prepared, seems fine, size-wise:
len(data.input_ids)
Out[31]: 320
data.input_ids[0]   # np array
Out[32]: 101

Question:
any clue why the error is saying "but the requested shape has 102400"?
Yes, the input tensors are indeed 320 in size, as serving function required, but why the function/calculation expect 102400 size?

Thanks again, appreciate your opinions and directions...
