### ISSUE TITLE
export error

### ISSUE THREAD

**Issue by hyybuaa** [bigboNed3/bert_serving#3]
Instructions for updating:
Pass your op to the equivalent parameter main_op instead.
INFO:tensorflow:Assets added to graph.
INFO:tensorflow:No assets to write.

**Comment by lpq29743** [comment]
Perhaps you export the model by the following way:
`estimator.export_savedmodel(FLAGS.export_dir, serving_input_fn())`
But Actually:
`estimator.export_savedmodel(FLAGS.export_dir, serving_input_fn)`
