### ISSUE TITLE
is there a way to accept the raw string rather than input_ids, segment_id, etc when using tf serving

### ISSUE THREAD

**Issue by bigtreeljc** [bigboNed3/bert_serving#9]

**Comment by RZachLamberty** [comment]
would also be very interested in an answer to this

**Comment by jageshmaharjan** [comment]
@RZachLamberty and @bigboNed3  , is this what you are looking for?
https://medium.com/analytics-vidhya/bert-rest-inference-from-the-fine-tuned-model-4b1f31151f97?source=friends_link&sk=09bd28763175b3d882f6b9fc77a9d81b
